"use client"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { usePathname } from "next/navigation"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

const menuList = [
  {
    title: "Home",
    path: "/",
  },
  {
    title: "User",
    path: "/user",
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // 根据路由切换 侧边栏 菜单 选中状态
  const pathname = usePathname()
  const menu = menuList.find((item) => item.path === pathname)

  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <div className="">
            <div className="header h-[60px] bg-gray-300">hello</div>
            <div className="content flex">
              <div
                className="left  bg-slate-400"
                style={{
                  height: "calc(100vh - 60px)",
                }}
              >
                {menuList.map((item) => {
                  return (
                    <div
                      className={`h-[60px] leading-[60px]   cursor-pointer hover:bg-[#3322ff]
                      ${menu?.path === item.path ? "bg-[#3366ff]" : ""}
                      text-white w-[200px] text-center border border-b border-[#fff]`}
                      key={item.title}
                    >
                      <Link href={item.path}>{item.title}</Link>
                    </div>
                  )
                })}
              </div>
              <div className="right flex-1">{children}</div>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
