import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { usePathname } from "next/navigation"
import Link from "next/link"
import Menu from "@/components/menu"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <div className="">
            <div className="header h-[60px] bg-gray-300">hello</div>
            <div className="content flex">
              <div
                className="lef"
                style={{
                  height: "calc(100vh - 60px)",
                }}
              >
                <Menu></Menu>
              </div>
              <div className="right flex-1">{children}</div>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
